apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: block-pvc
spec:
  storageClassName: csi-sc-cinderplugin-hiiops
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


(oc apply -f C:\Users\Owner\PycharmProjects\4\06\test_open_shift\infrastructure\yaml_for_pvc.yaml)